const express=require("express"),cors=require("cors"),fs=require("fs"),path=require("path");
const app=express(),PORT=5000,DATA_DIR=path.join(__dirname,"data"),DATA_FILE=path.join(DATA_DIR,"data.json");
app.use(cors());app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,"..","frontend")));
const seed={"users": [{"id": 1, "name": "System Admin", "email": "admin@resumeiq.com", "password": "admin123", "role": "ADMIN"}, {"id": 2, "name": "Demo User", "email": "user@resumeiq.com", "password": "user123", "role": "JOB_SEEKER"}], "jobs": [{"id": 1, "title": "Junior Web Developer", "company": "TechNova", "location": "Dhaka", "job_type": "Full-time", "salary": "৳25K–35K", "description": "Build and maintain modern web applications.", "required_skills": ["HTML", "CSS", "JavaScript", "Git"]}, {"id": 2, "title": "Frontend Developer Intern", "company": "PixelCraft", "location": "Remote", "job_type": "Internship", "salary": "৳12K–18K", "description": "Work with the frontend team on responsive interfaces.", "required_skills": ["HTML", "CSS", "JavaScript", "React"]}, {"id": 3, "title": "Java Software Engineer", "company": "SoftGrid", "location": "Dhaka", "job_type": "Full-time", "salary": "৳35K–50K", "description": "Develop enterprise Java applications.", "required_skills": ["Java", "SQL", "OOP", "Git"]}, {"id": 4, "title": "Backend Developer Intern", "company": "CloudByte", "location": "Remote", "job_type": "Internship", "salary": "৳15K–22K", "description": "Assist with REST API development.", "required_skills": ["Node.js", "Express", "SQL", "Git"]}, {"id": 5, "title": "Junior Python Developer", "company": "DataNest", "location": "Dhaka", "job_type": "Full-time", "salary": "৳30K–45K", "description": "Develop Python-based business applications.", "required_skills": ["Python", "SQL", "Git"]}], "resumes": [], "applications": [], "notifications": []};
function ensure(){if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});if(!fs.existsSync(DATA_FILE))fs.writeFileSync(DATA_FILE,JSON.stringify(seed,null,2),"utf8")}
const read=()=>{ensure();return JSON.parse(fs.readFileSync(DATA_FILE,"utf8"))},write=d=>{ensure();fs.writeFileSync(DATA_FILE,JSON.stringify(d,null,2),"utf8")};ensure();
app.get("/api/health",(q,s)=>s.json({status:"OK"}));
app.post("/api/auth/register",(q,s)=>{const name=String(q.body.name||"").trim(),email=String(q.body.email||"").trim().toLowerCase(),password=String(q.body.password||"");if(!name||!email||!password)return s.status(400).json({message:"All fields are required."});if(password.length<6)return s.status(400).json({message:"Password must be at least 6 characters."});const d=read();if(d.users.some(u=>u.email.toLowerCase()===email))return s.status(409).json({message:"Email already exists."});const id=Math.max(0,...d.users.map(u=>u.id))+1,u={id,name,email,password,role:"JOB_SEEKER"};d.users.push(u);write(d);s.status(201).json({message:"Account created successfully.",user:{id,name,email,role:u.role}})});
app.post("/api/auth/login",(q,s)=>{const email=String(q.body.email||"").trim().toLowerCase(),password=String(q.body.password||""),d=read(),u=d.users.find(x=>x.email.toLowerCase()===email&&x.password===password);if(!u)return s.status(401).json({message:"Invalid email or password."});s.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get("/api/jobs",(q,s)=>{const t=String(q.query.q||"").toLowerCase(),d=read();s.json(d.jobs.filter(j=>!t||[j.title,j.company,j.location,j.job_type,j.description,...j.required_skills].join(" ").toLowerCase().includes(t)))});
app.post("/api/applications",(q,s)=>{const userId=Number(q.body.userId),jobId=Number(q.body.jobId),d=read();if(!d.users.some(u=>u.id===userId))return s.status(404).json({message:"User not found."});if(!d.jobs.some(j=>j.id===jobId))return s.status(404).json({message:"Job not found."});if(d.applications.some(a=>a.userId===userId&&a.jobId===jobId))return s.status(409).json({message:"You already applied for this job."});d.applications.push({id:Math.max(0,...d.applications.map(a=>a.id))+1,userId,jobId,status:"APPLIED",appliedAt:new Date().toISOString()});write(d);s.status(201).json({message:"Application submitted successfully."})});
app.get("/api/applications/:id",(q,s)=>{const d=read(),u=Number(q.params.id);s.json(d.applications.filter(a=>a.userId===u).map(a=>({...a,job:d.jobs.find(j=>j.id===a.jobId)})))});
const skills=["HTML","CSS","JavaScript","Bootstrap","React","Java","SQL","OOP","Git","Node.js","Express","Python","Communication","Problem Solving","Teamwork"];
app.post("/api/analyze",(q,s)=>{const userId=Number(q.body.userId),text=String(q.body.resumeText||"").trim();if(!text)return s.status(400).json({message:"Please paste your resume text first."});const low=text.toLowerCase(),matched=skills.filter(x=>low.includes(x.toLowerCase())),missing=skills.filter(x=>!matched.includes(x)),score=Math.min(100,Math.round(matched.length/skills.length*75)+25),suggestions=[];if(!low.includes("education"))suggestions.push("Add a clear Education section.");if(!low.includes("experience"))suggestions.push("Add internship, project, or work experience.");if(!low.includes("project"))suggestions.push("Add 2–3 relevant projects.");const d=read();d.resumes.push({id:Math.max(0,...d.resumes.map(r=>r.id))+1,userId,resumeText:text,score,matched,missing});write(d);s.json({score,matched,missing,suggestions})});
app.get("/api/dashboard/:id",(q,s)=>{const d=read(),u=Number(q.params.id),r=d.resumes.filter(x=>x.userId===u),a=d.applications.filter(x=>x.userId===u);s.json({latestResumeScore:r.length?r[r.length-1].score:0,applications:a.length,shortlisted:a.filter(x=>x.status==="SHORTLISTED").length,jobs:d.jobs.length})});
app.get("*",(q,s)=>s.sendFile(path.join(__dirname,"..","frontend","index.html")));
app.listen(PORT,()=>console.log("ResumeIQ running at http://localhost:"+PORT));