CREATE DATABASE IF NOT EXISTS resumeiq CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE resumeiq;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,role ENUM('JOB_SEEKER','EMPLOYER','ADMIN') DEFAULT 'JOB_SEEKER',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS jobs(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(150) NOT NULL,company VARCHAR(150) NOT NULL,location VARCHAR(100) NOT NULL,job_type VARCHAR(50) NOT NULL,salary VARCHAR(100),description TEXT,required_skills VARCHAR(500) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS resumes(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,resume_text LONGTEXT NOT NULL,score INT DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS applications(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,job_id INT NOT NULL,status ENUM('APPLIED','REVIEWING','SHORTLISTED','REJECTED','HIRED') DEFAULT 'APPLIED',applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY unique_application(user_id,job_id));
